import { defineConfig, loadEnv } from 'vite';
import { resolve } from 'path';
import fs from 'fs';
import path from 'path';

// Marrakech Story is a "no-build" UMD React + Babel-in-browser app.
// Vite is only used so Hostinger detects a framework. The build step:
//   1. Copies every static asset (src/, assets/, styles.css) into dist/.
//   2. Generates dist/src/env.js from environment variables so the
//      Supabase URL + publishable key are baked in at build time
//      instead of being hard-coded in source.
//   3. Also copies admin.html if it exists.

function copyStaticTree() {
  const root = process.cwd();
  const include = ['src', 'assets', 'styles.css'];

  return {
    name: 'copy-static-tree',
    apply: 'build',
    closeBundle() {
      const outDir = path.resolve(root, 'dist');
      const copyRecursive = (src, dest) => {
        const stat = fs.statSync(src);
        if (stat.isDirectory()) {
          fs.mkdirSync(dest, { recursive: true });
          for (const f of fs.readdirSync(src)) {
            copyRecursive(path.join(src, f), path.join(dest, f));
          }
        } else {
          fs.mkdirSync(path.dirname(dest), { recursive: true });
          fs.copyFileSync(src, dest);
        }
      };
      for (const entry of include) {
        const from = path.resolve(root, entry);
        if (!fs.existsSync(from)) continue;
        const to = path.resolve(outDir, entry);
        copyRecursive(from, to);
      }
    }
  };
}

function generateEnvJs(env) {
  return {
    name: 'generate-env-js',
    apply: 'build',
    closeBundle() {
      const url = env.VITE_SUPABASE_URL || env.NEXT_PUBLIC_SUPABASE_URL || '';
      const key = env.VITE_SUPABASE_PUBLISHABLE_KEY || env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || '';
      if (!url || !key) {
        console.warn('[generate-env-js] No SUPABASE_URL / PUBLISHABLE_KEY in env — leaving dist/src/env.js untouched (will fall back to checked-in defaults).');
        return;
      }
      const content = `// Auto-generated by vite.config.js at build time. Do not edit.\nwindow.MS_ENV = {\n  SUPABASE_URL: ${JSON.stringify(url)},\n  SUPABASE_KEY: ${JSON.stringify(key)}\n};\n`;
      const outFile = path.resolve(process.cwd(), 'dist/src/env.js');
      fs.mkdirSync(path.dirname(outFile), { recursive: true });
      fs.writeFileSync(outFile, content);
      console.log('[generate-env-js] dist/src/env.js written from environment variables.');
    }
  };
}

export default defineConfig(({ mode }) => {
  // Load .env / .env.[mode] including all keys (no prefix filter) so we
  // can read both NEXT_PUBLIC_* and VITE_* style names.
  const env = loadEnv(mode, process.cwd(), '');
  return {
    appType: 'mpa',
    build: {
      outDir: 'dist',
      emptyOutDir: true,
      rollupOptions: {
        input: {
          main: resolve(process.cwd(), 'index.html'),
          fitness: resolve(process.cwd(), 'fitness.html')
        }
      }
    },
    plugins: [
      copyStaticTree(),
      generateEnvJs(env)
    ]
  };
});
