import { defineConfig, loadEnv } from 'vite';
import { resolve } from 'path';
import fs from 'fs';
import path from 'path';
import { compileJsxTree, rewriteHtmlScriptEntries } from './scripts/browser-js.mjs';

// Marrakech Story is a UMD React app served as precompiled browser scripts.
// Vite is only used so Hostinger detects a framework. The build step:
//   1. Copies every static asset (src/, assets/, styles.css) into dist/.
//   2. Generates dist/src/env.js from environment variables so the
//      Supabase URL + publishable key are baked in at build time
//      instead of being hard-coded in source.
//   3. Transpiles browser-facing JSX to plain JS that is safe for Safari/WebKit.
//   4. Builds both the public website and the dedicated admin entry.

function copyStaticTree() {
  const root = process.cwd();
  const include = ['src', 'assets', 'styles.css', 'apple-redesign.css', 'admin.css', 'robots.txt', 'sitemap.xml', 'googled9fb7d24e8ddbe07.html', 'site.webmanifest'];

  return {
    name: 'copy-static-tree',
    apply: 'build',
    closeBundle() {
      const outDir = path.resolve(root, 'dist');
      const copyRecursive = (src, dest) => {
        const stat = fs.statSync(src);
        if (stat.isDirectory()) {
          fs.mkdirSync(dest, { recursive: true });
          for (const f of fs.readdirSync(src)) {
            copyRecursive(path.join(src, f), path.join(dest, f));
          }
        } else {
          fs.mkdirSync(path.dirname(dest), { recursive: true });
          fs.copyFileSync(src, dest);
        }
      };
      for (const entry of include) {
        const from = path.resolve(root, entry);
        if (!fs.existsSync(from)) continue;
        const to = path.resolve(outDir, entry);
        copyRecursive(from, to);
      }
    }
  };
}

function generateEnvJs(env) {
  return {
    name: 'generate-env-js',
    apply: 'build',
    closeBundle() {
      const url = env.VITE_SUPABASE_URL || env.NEXT_PUBLIC_SUPABASE_URL || '';
      const key = env.VITE_SUPABASE_PUBLISHABLE_KEY || env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || '';
      const siteUrl = env.VITE_SITE_URL || env.NEXT_PUBLIC_SITE_URL || 'https://marrakechstory.com/';
      const adminUrl = env.VITE_ADMIN_URL || env.NEXT_PUBLIC_ADMIN_URL || 'https://marrakechstory.com/admin.html';
      if (!url || !key) {
        console.warn('[generate-env-js] No SUPABASE_URL / PUBLISHABLE_KEY in env — leaving dist/src/env.js untouched (will fall back to checked-in defaults).');
        return;
      }
      const extra = [
        `  SITE_URL: ${JSON.stringify(siteUrl)}`,
        `  ADMIN_URL: ${JSON.stringify(adminUrl)}`,
      ];
      const extraBlock = extra.length ? `,\n${extra.join(',\n')}` : '';
      const content = `// Auto-generated by vite.config.js at build time. Do not edit.\nwindow.MS_ENV = {\n  SUPABASE_URL: ${JSON.stringify(url)},\n  SUPABASE_KEY: ${JSON.stringify(key)}${extraBlock}\n};\n`;
      const outFile = path.resolve(process.cwd(), 'dist/src/env.js');
      fs.mkdirSync(path.dirname(outFile), { recursive: true });
      fs.writeFileSync(outFile, content);
      console.log('[generate-env-js] dist/src/env.js written from environment variables.');
    }
  };
}

function compileBrowserJsx() {
  const root = process.cwd();

  return {
    name: 'compile-browser-jsx',
    apply: 'build',
    async closeBundle() {
      await compileJsxTree({
        srcDir: path.resolve(root, 'src'),
        outDir: path.resolve(root, 'dist/src'),
        target: 'es2018',
      });
      rewriteHtmlScriptEntries(path.resolve(root, 'dist/index.html'));
      rewriteHtmlScriptEntries(path.resolve(root, 'dist/admin.html'));
    }
  };
}

export default defineConfig(({ mode }) => {
  // Load .env / .env.[mode] including all keys (no prefix filter) so we
  // can read both NEXT_PUBLIC_* and VITE_* style names.
  const env = loadEnv(mode, process.cwd(), '');
  return {
    appType: 'mpa',
    build: {
      outDir: 'dist',
      emptyOutDir: true,
      rollupOptions: {
        input: {
          main: resolve(process.cwd(), 'index.html'),
          admin: resolve(process.cwd(), 'admin.html'),
        }
      }
    },
    plugins: [
      copyStaticTree(),
      generateEnvJs(env),
      compileBrowserJsx()
    ]
  };
});
